name: karl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.36578701180405915
  saturation: 0.20576610090211034
  rhythmicContrast: 0.03945011249743402
purpose: []
